import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <section>{children}</section>
}
